### ISSUE TITLE
How to add limit to non list type?

### ISSUE THREAD

**Issue by xserosm** [join-monster/join-monster#106]
I have the following schema

```javascript
const Dialog = new GraphQLObjectType({
  description: 'A dialog type',
  name: 'Dialog',
  sqlTable: 'dialogs',
  uniqueKey: ['user_id', 'peer_user_id'],
  fields: () => ({
    lastMessage: {
      description: 'The last message',
      type: Message,
      orderBy: {
        date: 'DESC'
      },
      sqlJoin: (dialogsTable, messagesTable, args, { user }) => `
        ((
          ${messagesTable}.user_id = ${user.id} AND
          ${messagesTable}.peer_user_id = ${dialogsTable}.peer_user_id AND
          ${messagesTable}.deleted = FALSE
        ) OR (
          ${messagesTable}.user_id = ${dialogsTable}.peer_user_id AND
          ${messagesTable}.peer_user_id = ${user.id} AND
          ${messagesTable}.peer_deleted = FALSE
        ))
      `
    }
  })
})
```

It seems ok, in response I get one latest message, but according to debug logs all messages pulled out from DB:

generated query:
```sql
SELECT
 NULLIF(CONCAT("dialogs"."user_id", "dialogs"."peer_user_id"), '') AS "use#pee",
 "dialogs"."last_message_date" AS "last_message_date",
 "dialogs"."unread_messages_count" AS "unread_messages_count",
 "lastMessag"."id" AS "lastMessag__id",
 "lastMessag"."text" AS "lastMessag__text",
 "lastMessag"."date" AS "lastMessag__date",
 "lastMessag"."readed" AS "lastMessag__readed",
 "lastMessag"."peer_user_id" AS "lastMessag__peer_user_id"
FROM (
 SELECT *
 FROM dialogs "dialogs"
 WHERE "dialogs".user_id = 100
 ORDER BY "dialogs"."last_message_date" DESC
 LIMIT ALL
) "dialogs"
LEFT JOIN messages "lastMessag" ON
       ((
         "lastMessag".user_id = 100 AND
         "lastMessag".peer_user_id = "dialogs".peer_user_id AND
         "lastMessag".deleted = FALSE
       ) OR (
         "lastMessag".user_id = "dialogs".peer_user_id AND
         "lastMessag".peer_user_id = 100 AND
         "lastMessag".peer_deleted = FALSE
       ))
ORDER BY "dialogs"."last_message_date" DESC, "lastMessag"."date" DESC
```

And the result - `join-monster 9 rows...` (I have only 9 messages in DB)

How to prevent pulling all the messages if I need the latest one?

**Comment by acarl005** [comment]
There are a few options for you here:

1. Make the `JOIN` condition a bit more advanced such that it only produces one match. It could use a correlated subquery with a LIMIT. The first example from [this page](https://www.periscopedata.com/blog/4-ways-to-join-only-the-first-row-in-sql.html) has a nice example of doing that.

2. Rather than querying the `messages` table directly, you could create a `VIEW` and map a `GraphQLObject` type to this view. Such a view could, for example, contain only the latest message from each user.

3. If you don't mind making `messages` into a `Connection`, you could the pagination args to simply ask for the `first: 1`, but that would involve adding an `edges` and `node` fields in between, which can sometimes be intolerable.


There are a couple features in Join Monster I could add to make this easier:

 1. Add something very similar to the current pagination implementation but strip away the Connection parts such that it can only return the top *n* results as sorted by specified column(s).

2. Add an option to include row numbers, allowing the programmer to write `WHERE` conditions to filter on row numbers. This has the disadvantage of lacking portability.

I'd like to hear what people think about these.

**Comment by xserosm** [comment]
Thanks for help! The problem solved as described in first option.

What about features, I would prefer to have an ability to specify the number of returning lines in schema, rather than use additional query args

**Comment by xserosm** [comment]
@acarl005 Further tests showed, that subqueries in 'join' evaluated only once(postgres), so only one latest message over all messages(instead of within dialog) returned. I mean if I query the list of dialogs the response will contain all dialogs, but only one has the lastMessage(the latest message over all messages)

What do you think about to add something like ```limit: 1``` and use `LATERAL JOIN` in case if limit is specified?

**Comment by acarl005** [comment]
@xserosm 

> subqueries in 'join' evaluated only once(postgres)

Not always. It depends *where* in the `JOIN` clause the query occurs. A `JOIN` clause typically as two parts - a table expression and a boolean expression. If you place the `SELECT` in the table expression, it is treated as a derived table (which is not a correlated-subquery) and only executed once. If it's in the `ON` clause, **and** references the table on the left side of the join, it is a bona-fide correlated-subquery and may run once per row.

I was able to implement the suggested strategy in Postgres using the test schema from the documentation. Suppose you have a query like this that fetches all the posts for each user:

```sql
select
  a.id,
  p.id,
  p.body,
  p.created_at
from accounts a
join posts p
  on p.author_id = a.id
order by a.id, p.created_at desc;
```

I re-wrote this to use a correlated subquery such that it returns only the most recent post for each user:

```sql
select
  a.id,
  p.id,
  p.body,
  p.created_at
from accounts a
join posts p
  on p.id = (
    select id from posts
    where posts.author_id = a.id
    order by created_at desc
    limit 1
  );
```

I think you can use an analogous strategy.

> What do you think about to add something like limit: 1 and use LATERAL JOIN in case if limit is specified?

Yes, this is very possible and I would like to add something like in the future. However, additional feature development has been halted for a few weeks. I can get to it in a couple months at the latest. But I'll happily accept a PR!

**Comment by bennettrogers** [comment]
Hi @xserosm, would you mind sharing your solution using the correlated subquery? I'm trying to do something similar, but am having trouble getting the JOIN to return anything at all.
