### ISSUE TITLE
Can I use GraphQL for specifying table?

### ISSUE THREAD

**Issue by JeffML** [join-monster/join-monster#109]
I'm using this in my JavaScript:
```javascript
var schema = buildSchema(`
  type User {
    id: String
    name: String
  }

  type Query {
    user(id: String): User
  }
`);
```
If User is mapped to database table 'user', how would I specify that in this syntax?  Do I have to use a GraphQLObjectType instance instead?

**Comment by acarl005** [comment]
Yeah Join Monster's API was originally designed for using the classes in graphql-js, rather than the schema language. I created a separate package to help bridge the two: [join-monster-graphql-tools-adapter](https://github.com/acarl005/join-monster-graphql-tools-adapter).

This is only tested on Apollo's graphql-tools but I believe the two packages compile the schema language to the same target, so it should work.
