### ISSUE TITLE
Typescript Definition files

### ISSUE THREAD

**Issue by bradzacher** [join-monster/join-monster#135]
There's a number of gaps in your docs which skip out complete definitions for various fields and such.

Additionally some things are mentioned in your docs, but not actually defined anywhere. For example, in the docs you mention "The sqlTable can also be a function, i.e. a thunk.". But you don't mention anywhere that this thunk has arguments that are passed to it. You can only determine this by [digging into the library source](https://github.com/stems/join-monster/blob/d154299a0c4cd3c64256f8fa720dc0afd675d2a8/src/query-ast-to-sql-ast/index.js#L143-L148).

It'd be good if you guys could write something like a typescript definition file, so that there is a clearly defined schema which details exactly how the library works.

It'll also make it possible to use your library with typescript (currently users must write their own definitions, or live without types).

**Comment by acarl005** [comment]
Apologies for the incomplete documentation. I'm doing my best to keep it up to date. There are a number of things I need to update so I'll get to it when I'm able.

Regarding TypeScript: Stem uses Flow, which is a little more permissive with included libraries, rather than TypeScript. The team does not plan to maintain TypeScript definition files. If there is enough interest in this, we will accept a PR (as long as it's possible to keep the type definitions in entirely separate files).
