### ISSUE TITLE
How can I tell join monster not to generate table aliases ?

### ISSUE THREAD

**Issue by MichelWilleput** [join-monster/join-monster#152]
Hello,

The table aliases are generated and not available everywhere (like in an orderby function).
How can tell join monster not to generate table aliases ?
Anyway, i don't see the benefit of having aliases
Thanks

**Comment by acarl005** [comment]
The table aliases are necessary because two different fields might need to reference the same table. In those cases, the aliases are required for referencing the different sets sourced from that table.

That being said, aliases should not prevent you from using any of the supported join-monster features. `orderBy`, for example, does not need access to the alias. You simply need to return an object of the column names and the table alias will automatically prefix those column names.
