### ISSUE TITLE
How to query by where that require join?

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#197]
Hi,

I would glad to know if there's any good practice / dedicated feature to create query that finding based on another tables value, for ex:

I have User table that has 2 fields: id, email.
I have Comment table that have 2 fields: id, userId (fk).
I want to Comment object be queryable via User's id or **user's Email**.

Thanks!

**Comment by bw** [comment]
I'm not affiliated with join-monster, but FYI you can write a subquery into the join condition. This is what we do:

```js
where: (commentsTable) => `${commentsTable}.userId IN (SELECT id FROM users WHERE email = ?)`
```

**Comment by idangozlan** [comment]
Cool, thanks. I wish that join monster was have better handling of where queries. will think about idea and propose it here

**Comment by bw** [comment]
What we do at Conduit is actually to put all of the query conditions into the JOIN statement. Most of the time, the `where` behavior is not actually what you want because, if your `where` statement is too specific, your entire GraphQL query will return null. This happens even if it's just an inner query. Putting it on the JOIN solves this problem because the LEFT JOIN will not eliminate the left side of the response.

So I'd suggest you try that. We've written a whole framework to dynamically attach these query conditions depending on the situation. We push all of these conditions into an array and then reduce them into a string that we append to the JOIN.

**Comment by acarl005** [comment]
@idangozlan - As @bw mentioned, such a comparison can be done in the `JOIN` condition. Alternatively, you can use the fairly new [4th argument](http://join-monster.readthedocs.io/en/latest/API/#where) of the `where` function to access the parent table alias.

```js
{
  where(commentTbl, args, context, astNode) {
     // get some info on the parent node (or parent parent node, and so on)
    console.log(astNode.parent)

    return `${commentTbl}.user_email = ${astNode.parent.as}.email` // not exactly sure what goes here
  }
}
```
