### ISSUE TITLE
how to judge to use either joinMonster or sqlJoin in field in graphqlobject?

### ISSUE THREAD

**Issue by fangjj** [join-monster/join-monster#220]
how to judge to use either joinMonster or sqlJoin in field of graphqlobject? I just know use joinMonster in rootquery field, but the join-monster doc said it also can Handle a Sub-Field. then, i'm lost, can you explain the different Between the both?

**Comment by acarl005** [comment]
Calling `joinMonster` again begins a whole new round of data-fetching This is not advised because it will incur the "N+1 queries" problem a.k.a round-trip problem. `sqlJoin` uses a `JOIN` keyword in SQL in a single round-trip. `sqlBatch` will do a separate query, but rather than succumbing to the dreaded "N+1 queries" problem, it batches together the elements from a list using a `WHERE IN` clause, kind of similar to [DataLoader](https://github.com/facebook/dataloader)
