### ISSUE TITLE
Allow simple limit / offset pagination

### ISSUE THREAD

**Issue by amarsyla** [join-monster/join-monster#247]
I tried to use LIMIT / OFFSET using the first / after arguments for simple pagination, but it's not currently possible with mariadb. Currently, 'after' accepts only a string cursor, but it should also accept an integer for SQL offset.

**Comment by leonardfactory** [comment]
Quoting the docs:

> The Relay Cursor contains the offset and is therefore predictable. You can produce the cursor for any row in the middle because you can predict the offset value. graphql-relay has a helper for this. (..)

What's really going on with `after` and the cursor (if I've got the [pagination docs](http://join-monster.readthedocs.io/en/latest/pagination/) right), when you use `sqlPaginate: true`, is just a simple limit / offset with a base64 encoded cursor as graphql-relay specificates. 

You should not worry about it being a string, since:

- The cursor will be provided to you by the `endCursor` field in `pageInfo`; just add it to the query to get it out (so when you paginate you can just use it in the following query)
- The cursor is just an encoding, and as the example in the docs shows, you can determinate it given an offset using`graphql-relay` function `offsetToCursor`:

```js
import { offsetToCursor } from 'graphql-relay'

let cursor = offsetToCursor(9)

// jump straight to page 3!
let query = `{
  user(id: 1) {
    posts(first: 5, after: "${cursor}") {
      pageInfo {
        endCursor
      }
      total
      edges {
        node { body }
      }
    }
  }
}`
``` 

I hope I've answered your question.

**Comment by mposborne** [comment]
For anyone not using Relay but still wanting simple LIMIT / OFFSET, here's an example (rather rough) dialect you can use/modify to do that:

https://github.com/RollHQ/join-monster-mysql
