### ISSUE TITLE
does query planning is a way to handle bad query planning by database ?

### ISSUE THREAD

**Issue by xcombelle** [join-monster/join-monster#249]
I was reading https://join-monster.readthedocs.io/en/latest/query-planning/  
and wandered why making a two step request should be faster than a single step request with a correct query planning by the database.

Maybe I'm wrong, In an ideal world the query planer of the database should decompose the initial request in the same way that it is done in the two part request. 

Of what I understand of RDBMS, if the one step request is slower than second one is because the database query planer fail for example because the statistics off the database are not good enough.

**Comment by renato** [comment]
From https://join-monster.readthedocs.io/en/latest/query-planning/:
> This mitigates the exponential increase in the number of rows per join

Using the same single join example, as the join starts from the user, suppose there are 20 followers and 10 posts for that user, with 5 comments per post and 2 likes per comment, you'll have 1x20x10x5x2 rows (users x followers x posts x comments x likes) in that query, 2,000 rows with 18 fields each so you'll end up with 36,000 cells in your result set.

In the split queries, the first query would return 1x20x10 (users x followers x posts) = 200 rows with 10 fields each so 2,000 cells and the second one would return 5x2 (comments x likes) = 10 rows with 9 fields each so 90 cells.

The example is small but as the quoted statement said: it increases exponentially.

I'm ignoring how the database query planner works because it's interesting to avoid all this footprint to reduce bandwidth, traffic, memory, data type conversions and so on.

**Comment by xcombelle** [comment]
I understand, it multiplies because there is n followers and m posts for each user. It is the fact you have to independent 1-n relation ship that bring the overload. Maybe such situations could be detected automatically by the software.
