### ISSUE TITLE
Using with apollo-server

### ISSUE THREAD

**Issue by fortm** [join-monster/join-monster#25]
This looks very nice project. 

Had a doubt if it can this be used in [apollo-server](https://github.com/apollostack/graphql-server) Graphql schema like one in [Githunt example](https://github.com/apollostack/GitHunt-API/blob/master/api/sql/schema.js) [](url) by modifying existing schema  ?

**Comment by acarl005** [comment]
Currently Join Monster only works with schemas defined in the reference implementation, [graphql-js](https://github.com/graphql/graphql-js). Since it lets you define the schemas with plain old JavaScript objects, custom properties can be added on the type definitions - a necessity for adding metadata utilized by Join Monster.

The Schema Language doesn't let you add custom metadata and functions to your types in the same way. We encourage those who use the Schema Language to ideate on how we can bring these ideas to the Schema Language as well.

**Comment by dreamcodez** [comment]
I think the best way to handle this currently in lieu of a better solution is to first load the schema language, and have a separate file which can traverse the schema with the getType method, and attach properties from there. Its hacky but it will work just fine. The file could be named join-monster-annotations.js for example, and return a default function which takes a schema object to annotate.

Thoughts??

**Comment by migueloller** [comment]
@dreamcodez, take a look at the conversation in https://github.com/stems/join-monster/issues/12

**Comment by acarl005** [comment]
Apollo is now supported. For now, this is in a *separate package*.

See [join-monster-graphql-tools-adapter](https://github.com/acarl005/join-monster-graphql-tools-adapter).

For now I'll be plugging in compatibility with other GraphQL implementations in separate packages, or "adapters". They will not be included in the base join-monster package.
