### ISSUE TITLE
sqlPaginate not query LIMIT AND OFFSET STATEMENT.

### ISSUE THREAD

**Issue by halallahh** [join-monster/join-monster#28]
I have set **sqlPaginate** to **true** but look like LIMIT and OFFSET STATEMENT not run. Any missing part on my code below:

```javascript
// connectionArgs import from graphql-relay but I not using relay at all.
 comments: {
           sqlColumn: 'comments',
           args: connectionArgs,
           sqlPaginate: true,
           orderBy: 'id',
           type: CommentType,
           sqlJoin: (todoTable, commentTable) => `${todoTable}.id = ${commentTable}.todo_id`
}
```

Query (console.log): 
```
SELECT
  "todos"."id" AS "id",
  "todos"."task" AS "task",
  "comments"."id" AS "comments__id",
  "comments"."title" AS "comments__title"
FROM todos AS "todos"
LEFT JOIN comments AS "comments" ON "todos".id = "comments".todo_id
```

Dialect: pg

**Comment by halallahh** [comment]
We need to using graphql-relay to use LIMIT and OFFSET STATEMENT?
or any other ways to make resolver like this:
```
const RootQuery = new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
        todos: {
            type: new GraphQLList(TodoType),
            args: {
                limit: {
                    type: GraphQLInt
                },
                offset: {
                    type: GraphQLInt
                }
            },
            resolve(root, { limit, offset }, context, resolveInfo) {
                return joinMonster(resolveInfo, {}, sql => {
                    console.log(sql);
                    return knex.raw(`${sql} LIMIT ${limit} OFFSET ${offset}`)
                }, {dialect: 'pg'});
            }
        }
    })
});
```

**Comment by halallahh** [comment]
We need to using graphql-relay to use LIMIT and OFFSET statement?
or any other ways to make resolver like this:
```javascript
const RootQuery = new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
        todos: {
            type: new GraphQLList(TodoType),
            args: {
                limit: {
                    type: GraphQLInt
                },
                offset: {
                    type: GraphQLInt
                }
            },
            resolve(root, { limit, offset }, context, resolveInfo) {
                return joinMonster(resolveInfo, {}, sql => {
                    console.log(sql);
                    return knex.raw(`${sql} LIMIT ${limit} OFFSET ${offset}`)
                }, {dialect: 'pg'});
            }
        }
    })
});
```

**Comment by halallahh** [comment]
We need to using graphql-relay to use LIMIT and OFFSET statement?
or any other ways to make resolver like this:

```javascript
const RootQuery = new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
        todos: {
            type: new GraphQLList(TodoType),
            args: {
                limit: {
                    type: GraphQLInt
                },
                offset: {
                    type: GraphQLInt
                }
            },
            resolve(root, { limit, offset }, context, resolveInfo) {
                return joinMonster(resolveInfo, {}, sql => {
                    console.log(sql);
                    return knex.raw(`${sql} LIMIT ${limit} OFFSET ${offset}`)
                }, {dialect: 'pg'});
            }
        }
    })
});
```

**Comment by halallahh** [comment]
test

**Comment by acarl005** [comment]
What does the `CommentType` look like in this case?

Indeed, Relay does not need to be used as the GraphQL client. However, when Join Monster hydrates/shapes the data, it is going to shape it into an Object which conforms to the [relay connection specification](https://facebook.github.io/relay/graphql/connections.htm). Therefore, your `CommentType` cannot just be a list type. It must be an object type with a "edges" and a "pageInfo" field. You comments will be in the "node" field of "edges".

If you haven't already done this, it is easily done with `graphql-relay`

``` js
import { connectionDefinitions } from 'graphql-relay'

const { connectionType: CommentConnection } = connectionDefinitions({ nodeType: CommentType })
```

``` js
comments: {
  type: CommentConnection,
  args: connectionArgs,
  sqlPaginate: true,
  orderBy: 'id',
  sqlJoin: (todoTable, commentTable) => `${todoTable}.id = ${commentTable}.todo_id`
},
```

If the type does not fit the spec, it will ignore the pagination.

I updated Join Monster. Instead of ignoring the pagination, it will **throw an error** if there is an issue with meeting the relay spec. I would recommend updating to 0.5.2 now.

**Comment by halallahh** [comment]
We need to using graphql-relay to use LIMIT and OFFSET statement?
there is any other ways to make resolver like this:

``` javascript
const RootQuery = new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
        todos: {
            type: new GraphQLList(TodoType),
            args: {
                limit: {
                    type: GraphQLInt
                },
                offset: {
                    type: GraphQLInt
                }
            },
            resolve(root, { limit, offset }, context, resolveInfo) {
                return joinMonster(resolveInfo, {}, sql => {
                    console.log(sql);
                    return knex.raw(`${sql} LIMIT ${limit} OFFSET ${offset}`)
                }, {dialect: 'pg'});
            }
        }
    })
});
```

**Comment by acarl005** [comment]
No, it is not **necessary** to use the Relay Connection Spec for limit-offset pagination. It is a standard that we decided to adopt into Join Monster for two reasons:
1. Our front-end app is a Relay app.
2. It's really the only abundantly recognized **standard** at the moment. It is still useful if the front-end isn't relay. Its a standard that many other open-source libraries have adopted, including [PostGraphQL](https://github.com/calebmer/postgraphql)

So yes, for now Join Monster expects you to set up connections in a certain way in order to paginate. FYI, you are not required to use the helper functions from the [graphql-relay-js](https://github.com/graphql/graphql-relay-js) package. You can define the connection object manually with objects from plain old [graphql-js](https://github.com/graphql/graphql-js).

I see you've worked around this requirement.

Adding the LIMIT OFFSET clauses to the query manually may work for use use cases. If it satisfies yours, then thats great! However, it will not generalize to all schemas. If, for example, the Comment Type (which is paginated) has another nested field that requires an additional JOIN, adding a LIMIT OFFSET at the end of the query can not be used to paginate the comments. For example:

```
{
  todos {
    id
    task
    comments(limit: 10, offset:20) {
      id
      title
      likers {
        id
        name
      }
    }
  }
}
```

Say we had a list of people that liked a comment. If we also need to JOIN on those, trying to LIMIT OFFSET the comments will incorrectly remove likers from the result set. Furthermore, what if you **also** wanted to paginate the likers? This would be impossible.

But if you work with Join Monsters opinionated way of doing pagination, it will solve this. Using `LATERAL JOIN`s will solve this problem.

**Comment by halallahh** [comment]
Thanks for your explanation :+1:
