### ISSUE TITLE
Whats the purpose of refetching the id in nodeDefenitions? 

### ISSUE THREAD

**Issue by shakaIsReal** [join-monster/join-monster#42]
@acarl005 Amazing staff! Thanks for join-monster 

 But I don't get why there's a need to refetch the `id` in `nodeDefinitions`

```
const { nodeInterface, nodeField } = nodeDefinitions(
  // this function resolves an ID to an object
  (globalId, context, resolveInfo) => {
    // parse the globalID
    const { type, id } = fromGlobalId(globalId)
 
    return joinMonster.getNode(type, resolveInfo, context,
      table => `${table}.id = ${id}`,    // why? 
      sql => {
        if (context) {
          context.set('X-SQL-Preview', sql.replace(/\n/g, '%0A'))
        }
        return knex.raw(sql)
      },
      options
    )
  },
  // this function determines the type. `joinMonster` figures it out for you and attaches the type to the result in the "__type__" property
  obj => obj.__type__
)

```

Why not just return the `type` since we know it already? 

```
const { nodeInterface, nodeField } = nodeDefinitions(
  // this function resolves an ID to an object
  (globalId, context, resolveInfo) => {
const { type, id } = fromGlobalId(globalId);
return FunctionThatGetsObject(type)   // returns e.g UserType
} 
.... 
```

**Comment by acarl005** [comment]
@shakaIsReal thanks for the compliments!
The node interface is something the team and I are re-visiting.

Why write a function to generate the `WHERE` condition? Can't this be automated? The `uniqueKey` that join monster requires can be looked up from the type definition. It's possible as long as the GlobalID contains the value in the `uniqueKey` column.

Our concern was that some people might generate their GlobalIDs from something other than the column indicated in the `uniqueKey`. Trying to automate this probably would have been fine for 95% of schemas. We left it as a function to try and support everyone. Ultimately, it just makes this redundant and complicated for the 95% of use cases where it could've been automated.

Moving forward, we'll likely establish a convention to make writing the `where` function optional, so it'll just assume the column from the `uniqueKey`, or you could explicitly write the function if you want to.

**Comment by shakaIsReal** [comment]
@acarl005 Thanks, as I understand the only reason behind making queries  (using `id`) in nodeDefenitions is to check if the object exists in the database. Wouldn't that be checked anyway in the resolve function of a specific type that `obj.__type__`  returns?  Because now we are making 2 queries to db.

**Comment by acarl005** [comment]
There is only one database request being made. The purpose of the first function (the resolver) in `nodeDefinitions` is to fetch the record from the database. This can can be accomplished any number of database queries. Join Monster makes it only *one*. The second function, the `resolveType`, simply determines the GraphQL type given the object returned by the `resolver`, which does not require any database queries, it is inferred from the name. To avoid having to duplicate the logic manually, join monster figures out the type and assigns it to the `__type__` property on that object so that all you have to do to implement the `resolveType` is get the value on the `__type__` property. So it's only one query to fetch the data and figure out the type.

**Comment by shakaIsReal** [comment]
@acarl005 Thanks. Please see #45
