### ISSUE TITLE
Authorization for specific fields/nodes

### ISSUE THREAD

**Issue by shakaIsReal** [join-monster/join-monster#45]
In my case some users are private or public. If the user is private only accepted followers can view their content. Some fields such as `email` are only accessed by the creator. 
So before using join-monster my authorization logic looked like this: 

```
// UserType fields 

posts: { 
     type: new GraphQLList(PostType), 
     resolve(type, {viewer}) => getPosts(viewer, type.id) 
 },
email: { 
     type: GraphQLString, 
     resolve(type, {viewer}) => getEmail(viewer, type.id) 
 },
...
```
`getPosts` would check if viewer is allowed to see content (public/private) and `getEmail` would check if viewer is the owner. This allows to easily control what data is called from the database. 

Since join-monster gathers all fields together and creates one query, it's hard to control what data can be accessed and I haven't found any API for it. Do you have any suggestions? 

NB: I am using Relay.js

**Comment by acarl005** [comment]
This is one problem with this particular batching strategy. Any fine-grained authorization check must be done in the resolvers, after the request was made. Once the data is fetched, you can check the auth in the resolvers. If something is not allowed, you can `throw` an error or return `null` to remove it from the result. Although a bit wasteful, it works.

**Comment by shakaIsReal** [comment]
Thanks, still the amount of requests join-monster saves is worth using it! It'd be nice if authentication/checks can be done in higher level of `getNode()` and `joinMonster()` i.e. by passing options to them and having a `isAllowed` field  (with some logic) on each type. 
For example: 
```
// QueryType.js 

group: {  
 type: ..., 
resolve: (parent, args, context, resolveInfo) => {
const getOwner = await getOwner(args.id); // return { userId:1 }
return joinMonster(resolveInfo, context, sql => {
return knex.raw(sql)
}, { getOwner, auth, options: optionsData }) 
}
}

// GroupType.js 

members: { 
type: ... , 
isAllowed: (obj) => obj.userId = obj.auth 
}

```

But that would be hard to implement when using `nodeField`, since we don't know what options to pass in `getNode()` for different types...

**Comment by dreamcodez** [comment]
it should be possible to do acl check via an async where clause now to an extent -- since where clauses are async now you could do an acl check there and drop in scoping or even a FALSE based on the viewer access

**Comment by bs1180** [comment]
@shakaIsReal I'm using a combination of pre- and post- permission checks. As much as possible, I'm now modifying the where query so that only the permitted rows are ever fetched from the database.

For example, I have a multitenant app where the users are separated by a tenant_id field, and a simple filter restricts the data that is fetched:

```
where: (usersTable, args, { tenant, viewer }) => {
  let filter = `${usersTable}.tenant_id = ${tenant.id}`
  if (viewer.isAdmin()) {
    filter = filter + ` AND ${usersTable}.deleted_at IS NULL`
  }
  return filter
}, 
```
The tenant and viewer on the query context are populated outside of graphQL in the Express middleware. I feel it's a bit awkward having to concatenate strings to build the SQL statement but this is the most efficient data fetching method I've found so far. And with the recent release these statements can also be async, which allows all manner of permission checking.

At a field level, I also check in each resolve function:
```
dateOfBirth: {
  type: GraphQLString,
  description: 'Private field',
  resolve: (user, args, { tenant, viewer }) => {
    if (viewer.isAdmin() || viewer.id === user.id) {
      return user.dateOfBirth
    } else {
      throw new Error('Permissions error! You can't view this field')
    }
  }
}
```
I've actually refactored this to make it a higher order function, based on [this pattern](https://fabric.io/blog/productionizing-graphqljs-how-we-protect-customer-data-site-uptime).

As mentioned above, the resolve function is called only once join monster has already retrieved the records, so if someone did send a malicious request, the data is still fetched from the DB before the ACL is applied. For my purposes, this is acceptable.

There was a suggestion by one of the GraphQL Facebook team that authorization should be external to resolving the query, but I haven't seen any opensource tools that could do that. I'd love to see other examples of people are doing this at the moment.
