### ISSUE TITLE
Order By without Relay dependency

### ISSUE THREAD

**Issue by theobat** [join-monster/join-monster#61]
How hard would it be to add support for Order By without the relay dependency? 

*My use case is pretty simple, I have a bunch of states for an entity I would order them based on their creation date. Right now I don't see how to do that decently (I could annotate the query generated by join monster but that sounds like a bad idea)*. 

I feel like you don't **need** relay to support pagination in an app, and pagination is not the only use case for an ORDER BY in a join query anyway. I'd be happy to submit a PR if there is no red flag.

**Comment by maxpain** [comment]
+1

**Comment by theobat** [comment]
Ok, with hindsight you can hack with the where function of the api to pass an ORDER BY as long as you only order by the main table (the only one that is passed to the where function). So it seems #63 takes the precedence.

Of course it'd be better to have both #63 (that is to say - passing all the tables involved to the where function) and a dedicated orderBy function similar to the where already in the api but the latter can wait.

**Comment by acarl005** [comment]
@theobat This is a bit confusing in the docs. Join Monster does not require you to use Relay to support pagination. Rather, it uses Relay's *specification* for pagination. Relay's specification requires you to have specific Object types called Connection types that have specific fields, i.e. `pageInfo`, `hasNextPage`. Join Monster conforms to this particular interface. It does not matter if Relay happens to be the GraphQL client consuming this API. So you can go ahead and paginate without Relay.

Currently `ORDER BY` outside of the paginated subqueries are not supported. You can sort the results in your resolvers. Yes, this wastes your servers' CPU cycles. It would be much more efficient to do the sorting in the DBMS where it could take advantage of ordered indexes. We didn't implement this because it got very complicated. What if multiple tables want to order? What if it gets mixed with pagination? We hope to work this out. But for now, ordering can be done in the application layer.

**Comment by acarl005** [comment]
@theobat @Maxpain177 
`ORDER BY` clauses are now generally supported with the `orderBy` property in **v1.0.1**, even for non-paginated fields. See [this page](http://join-monster.readthedocs.io/en/latest/order-by/) in the docs for details.
