### ISSUE TITLE
support for DataLoaders?

### ISSUE THREAD

**Issue by paOol** [join-monster/join-monster#92]
does this automatically make use of, or allow for Data Loaders?

https://www.youtube.com/watch?v=c35bj1AT3X8&feature=youtu.be&t=41m35s

**Comment by acarl005** [comment]
@paOol 

> does this automatically make use of

No. Join Monster implements its own batching mechanisms similar to DataLoader. The differences are that it the SQL is generated dynamically based on the fields actually requested by the client and individual records are not automatically cached. Join Monster allows you to JOIN on multiple object types within each batch, meaning you can achieve fewer round-trips to the database (as few as a single SQL query) than you can with DataLoader.

> or allow for Data Loaders?

Yes. From the README, Join Monster "coexists with your custom resolve functions and existing schemas. Use it on the whole graph or only in parts. Retain the power and expressiveness in defining your schema." Since you can write `resolve` functions as normal that work alongside join-monster, you can utilize DataLoader in those resolve functions.

**Comment by tonyxiao** [comment]
This is what makes join-monster so amazing and flexible. Thank you @acarl005
